# Generated by Django 4.0.4 on 2022-06-04 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiles',
            options={'ordering': ['created']},
        ),
    ]
