# Generated by Django 4.0.4 on 2022-06-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profiles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiles',
            options={'ordering': ['up_vote', 'created']},
        ),
        migrations.AddField(
            model_name='profiles',
            name='up_vote',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
