# Generated by Django 4.0.4 on 2022-06-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profiles_options_profiles_up_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='up_vote',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
