# Generated by Django 4.0.4 on 2022-09-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiless',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
